
PREFIX=
CC=$(PREFIX)gcc
CXX=$(PREFIX)g++
COBJS=./hidapi/mac/hid.o
CPPOBJS=./hid2hcix.o
OBJS=$(COBJS) $(CPPOBJS)
CFLAGS=-Ihidapi/hidapi -g -c
LIBS= -framework IOKit -framework CoreFoundation

.PHONY: all clean

all: hid2hcix

clean:
	rm -f $(COBJS)
	rm -f $(CPPOBJS)
	rm -f hid2hcix

hid2hcix: $(OBJS)
	$(CXX) -g $^ $(LIBS) -o hid2hcix

$(COBJS): %.o: %.c
	$(CC) $(CFLAGS) $< -o $@

$(CPPOBJS): %.o: %.cpp
	$(CXX) $(CFLAGS) $< -o $@

